# Generated by Django 5.0.6 on 2024-11-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_remove_team_age_team_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='postion',
            new_name='position',
        ),
    ]
